### ISSUE TITLE
Potentially unhandled rejection [1] TypeError: Cannot read property 'context' of undefined

### ISSUE THREAD

**Issue by tomoat** [static-dev/spike-records#39]
``` js
const path = require('path')
const HardSourcePlugin = require('hard-source-webpack-plugin')
const htmlStandards = require('reshape-standard')
const cssStandards = require('spike-css-standards')
const jsStandards = require('babel-preset-latest')
const pageId = require('spike-page-id')
const Records = require('spike-records')
const locals = {}

module.exports = {
  devtool: 'source-map',
  matchers: {
    html: '*(**/)*.sgr',
    css: '*(**/)*.sss'
  },
  ignore: ['**/layout.sgr', '**/layouts/*', '**/test/*', '**/includes/*', '**/_*', '**/.*', '_cache/**', 'readme.md'],
  reshape: (ctx) => {
    return htmlStandards({
      webpack: ctx,
      locals: Object.assign({ pageId: pageId(ctx), foo: 'bar' }, locals)
    })
  },
  /*reshape: (ctx) => htmlStandards({ locals }),*/
  postcss: (ctx) => {
    return cssStandards({ webpack: ctx })
  },
  babel: { presets: [jsStandards] },
  plugins: [
    new HardSourcePlugin({
      environmentPaths: { root: __dirname },
      recordsPath: path.join(__dirname, '_cache/records.json'),
      cacheDirectory: path.join(__dirname, '_cache/hard_source_cache')
    }),
    new Records({
        addDataTo: locals,
      staff: {
        url: 'http://api.bycarrot.com/staff',
        template: {
          transform: (data) => { return data.data },
          path: 'views/_article_detail.sml',
          output: (staff) => { return `post/${staff.id}`}
        }
      }
    })
  ],
  server: { open: false }
}
```

``` bash
➜  test-project spike watch
Potentially unhandled rejection [1] TypeError: Cannot read property 'context' of undefined
    at pageId (/Users/tomato/Sites/spike-test/test-project/node_modules/spike-page-id/lib/index.js:2:49)
    at Object.reshape (/Users/tomato/Sites/spike-test/test-project/app.js:28:39)
    at Object.parseOptions (/Users/tomato/Sites/spike-test/test-project/node_modules/reshape-loader/lib/index.js:51:55)
    at W.map (/Users/tomato/Sites/spike-test/test-project/node_modules/spike-records/lib/index.js:86:45)
    at tryCatch2 (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/makePromise.js:833:12)
    at mapAt (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/makePromise.js:227:40)
    at traverseAt (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/makePromise.js:247:6)
    at traverseWith (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/makePromise.js:216:5)
    at Function.traverse [as _traverse] (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/makePromise.js:198:11)
    at Function.map (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/decorators/array.js:197:19)
    at /Users/tomato/Sites/spike-test/test-project/node_modules/when/when.js:207:19
    at tryCatchReject (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/makePromise.js:592:4)
    at ContinuationTask.run (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/makePromise.js:702:24)
    at Scheduler._drain (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/Scheduler.js:62:19)
compiled (0.663s)
▸ External IP: http://192.168.12.104:1111
```

**Comment by tomoat** [comment]
> template: {
>           transform: (data) => { return data.data },
>           path: 'views/_article_detail.sml',
>           output: (staff) => { return `post/${staff.id}`}
>         }

Increase the problem after this section of code

**Comment by jescalan** [comment]
Hi @tomoat! This is an issue that happens when using `spike-page-id`, if I'm not mistaken. I can have it ironed out soon, sorry about that!

**Comment by tomoat** [comment]
``` js
const path = require('path')
const HardSourcePlugin = require('hard-source-webpack-plugin')
const htmlStandards = require('reshape-standard')
const cssStandards = require('spike-css-standards')
const jsStandards = require('babel-preset-latest')
const Records = require('spike-records')
const locals = {}

module.exports = {
  devtool: 'source-map',
  matchers: {
    html: '*(**/)*.sgr',
    css: '*(**/)*.sss'
  },
  ignore: ['**/layout.sgr', '**/layouts/*', '**/test/*', '**/includes/*', '**/_*', '**/.*', '_cache/**', 'readme.md'],
  reshape: (ctx) => {
    return htmlStandards({
      webpack: ctx,
      locals: Object.assign({ foo: 'bar' }, locals)
    })
  },
  /*reshape: (ctx) => htmlStandards({ locals }),*/
  postcss: (ctx) => {
    return cssStandards({ webpack: ctx })
  },
  babel: { presets: [jsStandards] },
  plugins: [
    new HardSourcePlugin({
      environmentPaths: { root: __dirname },
      recordsPath: path.join(__dirname, '_cache/records.json'),
      cacheDirectory: path.join(__dirname, '_cache/hard_source_cache')
    }),
    new Records({
      addDataTo: locals,
      staff: {
        url: 'http://api.bycarrot.com/staff',
        template: {
          transform: (data) => { return data.data },
          path: 'views/_article_detail.sml',
          output: (staff) => { return `post/${staff.id}`}
        }
      }
    })
  ],
  server: { open: false }
}
```

``` bash
test-project spike watch
✗ ERROR
Potentially unhandled rejection [178] TypeError: Cannot read property 'content' of undefined
    at beautifyPlugin (/Users/tomato/Sites/spike-test/test-project/node_modules/reshape-beautify/lib/index.js:10:16)
    at W.reduce (/Users/tomato/Sites/spike-test/test-project/node_modules/reshape/lib/index.js:43:60)
    at tryCatchResolve (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/apply.js:46:23)
    at callAndResolve (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/apply.js:30:12)
    at callAndResolveNext (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/apply.js:40:4)
    at tryCatchReject3 (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/makePromise.js:856:7)
    at runContinuation3 (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/makePromise.js:814:4)
    at Fulfilled.fold (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/makePromise.js:588:4)
    at callAndResolve (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/apply.js:34:12)
    at callAndResolveNext (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/apply.js:40:4)
    at tryCatchReject3 (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/makePromise.js:856:7)
    at runContinuation3 (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/makePromise.js:814:4)
    at Fulfilled.fold (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/makePromise.js:588:4)
    at callAndResolve (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/apply.js:34:12)
    at callAndResolveNext (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/apply.js:40:4)
    at tryCatchReject3 (/Users/tomato/Sites/spike-test/test-project/node_modules/when/lib/makePromise.js:856:7)
compiled (4.075s)
```

Not use `spike-page-id` module， There will still be the problem

**Comment by jescalan** [comment]
Ok this should be solved by the most recent merged PR, which just got shipped out 🎉
