### ISSUE TITLE
Can't get it working with fresh Spike + docs most basic example

### ISSUE THREAD

**Issue by corysimmons** [static-dev/spike-records#74]
```js
// app.js
const htmlStandards = require('reshape-standard')
const cssStandards = require('spike-css-standards')
const jsStandards = require('spike-js-standards')
const pageId = require('spike-page-id')
const env = process.env.NODE_ENV
const Records = require('spike-records')

const locals = {}

module.exports = {
  devtool: 'source-map',
  ignore: ['**/layout.html', '**/_*', '**/.*', 'readme.md', 'yarn.lock'],
  plugins: [
    new Records({
      addDataTo: locals,
      three: { data: { foo2: 'bar2' } }
    })
  ],
  reshape: htmlStandards({
    locals: (ctx) => {
      return {
        pageId: pageId(ctx),
        foo: 'bar'
      }
    },
    minify: env === 'production'
  }),
  postcss: cssStandards({
    minify: env === 'production',
    warnForDuplicates: env !== 'production'
  }),
  babel: jsStandards()
}
```

```html
<!-- index.html -->
<extends src='layout.html'>
  <block name='content'>
    <h2>Hello World!</h2>
    <p>Thanks for using <a href='https://github.com/static-dev/spike'>spike</a></p>
    <p>Example of locals: {{ three.foo2 }}</p>
    <p mdi> Example of **markdown**</p>
    <p>Example of "smart quotes" -- and dashes</p>

    <hr>

    <h3>Getting Started</h3>
    <h4>The Stack:</h4>
    <ul>
      <li><a href="https://reshape.ml">reshape</a> for HTML transforms</li>
      <li><a href="https://babeljs.io">babel</a> for JS transforms</li>
      <li><a href="http://postcss.org">postcss</a> for CSS transforms</li>
      <li><a href="http://webpack.github.io">webpack</a> for JS bundling</li>
    </ul>

    <p>Customize your settings by editing the <a href="https://spike.readme.io/docs/appjs">app.js</a> file or simply start by editing this view</p>
  </block>
</extends>
```

```bash
$ spike watch

✗ ERROR
{ ModuleBuildError: Module build failed: TypeError: Cannot read property 'foo2' of undefined
    at eval (eval at module.exports (/Users/tink/Desktop/tinker/spike/node_modules/reshape-code-gen/lib/scoped_eval.js:9:10), <anonymous>:1:157)
    at eval (eval at module.exports (/Users/tink/Desktop/tinker/spike/node_modules/reshape-code-gen/lib/scoped_eval.js:9:10), <anonymous>:1:171)
    at evalNode (/Users/tink/Desktop/tinker/spike/node_modules/reshape-eval-code/lib/index.js:27:72)
    at util.modifyNodes (/Users/tink/Desktop/tinker/spike/node_modules/reshape-eval-code/lib/index.js:21:40)
    at when.resolve.then (/Users/tink/Desktop/tinker/spike/node_modules/reshape-plugin-util/lib/index.js:26:29)
    at tryCatchReject (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/makePromise.js:592:4)
    at ContinuationTask.run (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/makePromise.js:702:24)
    at Scheduler._drain (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/Scheduler.js:62:19)
    at runLoaders (/Users/tink/Desktop/tinker/spike/node_modules/webpack/lib/NormalModule.js:194:19)
    at /Users/tink/Desktop/tinker/spike/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/tink/Desktop/tinker/spike/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/tink/Desktop/tinker/spike/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at tryCatchReject (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/Scheduler.js:27:9) id: '79c9335f' }
⚠ WARNING
{ ModuleBuildError: Module build failed: TypeError: Cannot read property 'foo2' of undefined
    at eval (eval at module.exports (/Users/tink/Desktop/tinker/spike/node_modules/reshape-code-gen/lib/scoped_eval.js:9:10), <anonymous>:1:157)
    at eval (eval at module.exports (/Users/tink/Desktop/tinker/spike/node_modules/reshape-code-gen/lib/scoped_eval.js:9:10), <anonymous>:1:171)
    at evalNode (/Users/tink/Desktop/tinker/spike/node_modules/reshape-eval-code/lib/index.js:27:72)
    at util.modifyNodes (/Users/tink/Desktop/tinker/spike/node_modules/reshape-eval-code/lib/index.js:21:40)
    at when.resolve.then (/Users/tink/Desktop/tinker/spike/node_modules/reshape-plugin-util/lib/index.js:26:29)
    at tryCatchReject (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/makePromise.js:592:4)
    at ContinuationTask.run (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/makePromise.js:702:24)
    at Scheduler._drain (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/Scheduler.js:62:19)
    at runLoaders (/Users/tink/Desktop/tinker/spike/node_modules/webpack/lib/NormalModule.js:194:19)
    at /Users/tink/Desktop/tinker/spike/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/tink/Desktop/tinker/spike/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/tink/Desktop/tinker/spike/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at tryCatchReject (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/tink/Desktop/tinker/spike/node_modules/when/lib/Scheduler.js:27:9) id: '79c9335f' }
```

Not sure if I'm including the `plugins` array at the right place or if it needs to go into `reshape.webpack` or something.

**Comment by corysimmons** [comment]
Oh never mind, I was trying to reassign `locals` or something. :X

```js
const htmlStandards = require('reshape-standard')
const cssStandards = require('spike-css-standards')
const jsStandards = require('spike-js-standards')
const pageId = require('spike-page-id')
const env = process.env.NODE_ENV
const Records = require('spike-records')

const locals = {}

module.exports = {
  devtool: 'source-map',
  ignore: ['**/layout.html', '**/_*', '**/.*', 'readme.md', 'yarn.lock'],
  reshape: htmlStandards({
    locals: ctx => Object.assign(locals, {
      pageId: pageId(ctx),
      foo: 'bar'
    }),
    minify: env === 'production'
  }),
  plugins: [
    new Records({
      addDataTo: locals,
      three: { data: { foo2: 'bar2' } }
    })
  ],
  postcss: cssStandards({
    minify: env === 'production',
    warnForDuplicates: env !== 'production'
  }),
  babel: jsStandards()
}
```

Works as expected.
